# Generated by Django 3.2.20 on 2023-09-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleIAPProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('product_id', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
