# Generated by Django 2.2.24 on 2022-04-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_auto_20220423_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='source',
            field=models.CharField(blank=True, choices=[('local', 'Local'), ('vimeo', 'Vimeo'), ('youtube', 'Youtube')], default='local', max_length=25, null=True),
        ),
    ]
