# Generated by Django 2.2.24 on 2022-04-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_video_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
    ]
